# permissions for end users to view resourcewatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcewatcher-viewer-role
rules:
- apiGroups:
  - ibm.dev.asset.ibm
  resources:
  - resourcewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibm.dev.asset.ibm
  resources:
  - resourcewatchers/status
  verbs:
  - get
